--1

SELECT e.Last_NAME ,e.employee_id ,M.nomJ , M.idJ 
FROM (SELECT  last_NAME as nomJ ,E.MANAGER_ID as idJ
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID 
WHERE E.MANAGER_ID IN ( SELECT MANAGER_ID FROM EMPLOYEES )
group by last_name,e.manager_id) M, EMPLOYEES E
INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID 
where e.manager_id=m.idj ;

whalen  101
khoo     114
colmenares  114

2--
SELECT e.Last_NAME ,e.employee_id ,M.nomJ , M.idJ 
FROM (SELECT  last_NAME as nomJ ,E.MANAGER_ID as idJ
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID 
WHERE E.MANAGER_ID not IN ( SELECT MANAGER_ID FROM EMPLOYEES )
group by last_name,e.manager_id) M, EMPLOYEES E
INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID 
where e.manager_id=m.idj ;
3--

4-
select d.department_id,e.last_name,job_title from employees e
inner join departments d on e.department_id = d.department_id
inner join jobs j on e.job_id=j.job_id
where d.department_id in (SELECT department_id from departments 
where department_name like '%Executive');
5-

SELECT last_name,
   CASE job_id
               WHEN  'AD_PRES' THEN 1
               WHEN  'SA_MAN' THEN 2
               WHEN  'IT_PROG' THEN 3
               WHEN  'SA_REP' THEN  4
               WHEN  'ST_CLERK' THEN 5
               else   0
               end  CATEGORIA from employees;
               









































SELECT FIRST_NAME AS EMPLEADO, DEPARTMENT_NAME AS NOMBRE_DEPARTAMENTO,E.MANAGER_ID AS JEFE
FROM EMPLOYEES E
INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID 
WHERE E.MANAGER_ID IN ( SELECT MANAGER_ID FROM EMPLOYEES WHERE JOB_ID LIKE ('%CLERK'));

--2
SELECT FIRST_NAME AS EMPLEADO,SALARY AS SALARIO,'MAYOR AL' , P.PROM AS PROMEDIO_DEPARTAMENTO 
FROM EMPLOYEES E, (SELECT DEPARTMENT_ID,AVG(SALARY) AS PROM FROM EMPLOYEES GROUP BY DEPARTMENT_ID) P 
WHERE SALARY >P.PROM AND P.DEPARTMENT_ID=E.DEPARTMENT_ID;

--3
SELECT FIRST_NAME AS NOMBRE,LAST_NAME AS APELLIDO,SALARY AS SALARIO,M.DEPARTMENT_ID, M.MINIMO_SALARIO 
FROM EMPLOYEES E, (SELECT DEPARTMENT_ID,MIN(SALARY) AS MINIMO_SALARIO FROM EMPLOYEES GROUP BY DEPARTMENT_ID) M
WHERE E.DEPARTMENT_ID=M.DEPARTMENT_ID 
ORDER BY E.DEPARTMENT_ID;

--4
SELECT DEPARTMENT_NAME,'EL EMPLEADO:',FIRST_NAME AS NOMBRE,'GANA  ',SALARY 
FROM DEPARTMENTS D 
INNER JOIN EMPLOYEES E ON E.DEPARTMENT_ID=D.DEPARTMENT_ID WHERE SALARY>10000 
ORDER BY DEPARTMENT_NAME